version: '3'
services:
  iron:
    build:
      context: docker
      dockerfile: Dockerfile.iron
    tty: true
#
#  rolling:
#    build:
#      context: docker
#      dockerfile: Dockerfile.rolling
#    tty: true

  sound:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./sounds:/root/sounds
      - ./scripts/sound:/root/scripts/sound
      - ./docker/middleware_profiles:/usr/local/share/middleware_profiles
    devices:
      - /dev/snd:/dev/snd
    command: pm2-runtime /root/scripts/sound/sound.json
    tty: true
    environment:
      - ROS_DOMAIN_ID=32
      - FASTRTPS_DEFAULT_PROFILES_FILE=/usr/local/share/middleware_profiles/rtps_udp_profile.xml
      - ALSA_CARD=2
    network_mode: host
